on:
  workflow_dispatch:

name: Test
jobs:
  test_clojure:
    name: Test Clojure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rlwrap
        run: sudo apt-get install -y rlwrap
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: latest
      - name: Run tests
        run: for dir in ${PWD}/*/clojure; do pushd ${dir} && ./run.sh && popd; done
